version: "3.9"

services:
  api:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DEBUG=${DEBUG}
      - MSSQL_HOST=${MSSQL_HOST}
      - MSSQL_DATABASE=${MSSQL_DATABASE}
      - MSSQL_USER=${MSSQL_USER}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
  #   depends_on:
  #     - db

  # db:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   ports:
  #     - 1433:1433
  #   container_name: mssql
  #   environment:
  #     - ACCEPT_EULA=${ACCEPT_EULA}
  #     - MSSQL_PID=${MSSQL_PID}
  #     - MSSQL_PORT=${MSSQL_PORT}
  #     - MSSQL_USER=${MSSQL_USER}
  #     - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
  #     - MSSQL_HOST=${MSSQL_HOST}
  #     - MSSQL_DATABASE=${MSSQL_DATABASE}
  #   hostname: db
  #   volumes:
  #     - mssql-data:/var/opt/mssql
  #   restart: always

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - api
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static

volumes:
  mssql-data:
  static-data: