# Generated by Django 4.1.9 on 2023-06-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('brand', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('warranty', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('processor', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('ram', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('harddrive', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='hardDrive')),
                ('grapcard', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='grapCard')),
                ('capgrapcard', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='capGrapCard')),
                ('opsystem', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='opSystem')),
                ('screensize', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='screenSize')),
                ('price_cops_field', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='price (COPs)')),
                ('ram_gb_field', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ram (GB)')),
                ('warranty_meses_field', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='warranty (meses)')),
                ('screensize_pulgadas_field', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='screenSize (Pulgadas)')),
                ('marketplace', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='marketPlace')),
            ],
            options={
                'db_table': 'Laptops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('embed_url', models.URLField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
    ]
