# Generated by Django 4.1.9 on 2023-06-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptops',
            options={'managed': False, 'verbose_name': 'Laptop', 'verbose_name_plural': 'Laptops'},
        ),
    ]
