# Generated by Django 4.1.9 on 2023-06-21 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_dashboard_created_at_dashboard_last_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
