# Generated by Django 4.1.9 on 2023-06-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_alter_dashboard_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laptops',
        ),
    ]
