# Generated by Django 4.1.9 on 2023-06-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_laptops_alter_dashboard_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='embed_url',
            field=models.TextField(blank=True),
        ),
    ]
